sky:
  datasource:
    # 数据库连接驱动类名称，这里使用的是 MySQL 的 JDBC 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库服务器地址
    host: localhost
    # 数据库服务器端口，MySQL 默认端口是 3306
    port: 3306
    # 要连接的数据库名称
    database: sky_take_out
    # 数据库用户名
    username: root
    # 数据库用户密码，注意：实际生产环境中不应直接暴露密码
    password: 123456

  alioss:
    # 阿里云 OSS 服务的终端节点，用于指定 OSS 服务的地域节点
    endpoint: 
    # 阿里云账号的 AccessKey ID，用于 OSS 身份验证
    access-key-id: 
    # 与 AccessKey ID 配套的 AccessKey Secret，同样用于 OSS 身份验证
    access-key-secret: 
    # OSS 中存储桶（Bucket）的名称
    bucket-name: 

  redis:
    # Redis 服务器的 IP 地址
    host: localhost
    # Redis 服务器的端口，默认为 6379
    port: 6379
    # 指定使用Redis的哪个数据库
    database: 10

  # 微信应用配置信息
  wechat:
    appid: 
    secret: 
    mchid: 
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
